[package]
name = "r_file_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
kafka = "0.9.0"
notify = "5.0.0"
rdkafka = "0.28.0"
yaml-rust = "0.4.5"
